apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdk 36
    namespace 'com.examsa.examsaideapp'

    defaultConfig {
        applicationId 'com.examsaide.app'
        minSdk 24
        targetSdk 36
        versionCode 3
        versionName "1.0.2"
    }

    signingConfigs {
        release {
            def keystoreFile = System.getenv("KEYSTORE_PATH") ?: ""
            storeFile keystoreFile ? file(keystoreFile) : null
            storePassword System.getenv("KEY_STORE_PASSWORD") ?: ""
            keyAlias System.getenv("KEYSTORE_ALIAS") ?: ""
            keyPassword System.getenv("KEY_PASSWORD") ?: ""
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation platform('com.google.firebase:firebase-bom:33.1.0')
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}
